server:
  port: 8088
spring:
  #????????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shops?useUnicode=true&characterEncoding=utf-8&userSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    #????????????InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #????????sql??
    show-sql: true
    hibernate:
      #??????????????????????????
      #ddl-auto: update

